// Auto-extracted from https://docs.adyen.com/platforms/verification-requirements/reference-additional-products/industry-codes
// (fetched 2026-08-13) — every value Adyen accepts for a business line's
// industryCode, grouped by sector for the business-activity select. Codes
// flagged approvalNeeded need sign-off from Adyen before they can be used
// in production (see the docs page) — surfaced in the option label rather
// than filtered out, so the full official list stays selectable as-is.
export type IndustryCode = {
  code: string;
  sector: string;
  description: string;
  approvalNeeded: boolean;
};

export const INDUSTRY_CODES: IndustryCode[] = [
  { code: "11", sector: "11 Agriculture, Forestry, Fishing and Hunting", description: "Agriculture, Forestry, Fishing and Hunting", approvalNeeded: false },
  { code: "21", sector: "21 Mining, Quarrying, and Oil and Gas Extraction", description: "Mining, Quarrying, and Oil and Gas Extraction", approvalNeeded: false },
  { code: "2211", sector: "22 Utilities", description: "Electric Power Generation, Transmission and Distribution", approvalNeeded: false },
  { code: "2212", sector: "22 Utilities", description: "Natural Gas Distribution", approvalNeeded: false },
  { code: "2213", sector: "22 Utilities", description: "Water, Sewage and Other Systems", approvalNeeded: false },
  { code: "23", sector: "23 Construction", description: "Construction & Installation (General Contractors)", approvalNeeded: false },
  { code: "23A", sector: "23 Construction", description: "Construction & Installation (Heating, Plumbing, and Air Conditioning Contractors)", approvalNeeded: false },
  { code: "23B", sector: "23 Construction", description: "Construction & Installation (Electrical Contractors)", approvalNeeded: false },
  { code: "23C", sector: "23 Construction", description: "Construction & Installation (Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors)", approvalNeeded: false },
  { code: "23D", sector: "23 Construction", description: "Construction & Installation (Carpentry Contractors)", approvalNeeded: false },
  { code: "23E", sector: "23 Construction", description: "Construction & Installation (Roofing, Siding, and Sheet Metal Work Contractors)", approvalNeeded: false },
  { code: "23F", sector: "23 Construction", description: "Construction & Installation (Concrete Work Contractors)", approvalNeeded: false },
  { code: "23G", sector: "23 Construction", description: "Construction & Installation (Special Trade Contractors)", approvalNeeded: false },
  { code: "3121A", sector: "31-33 Manufacturing", description: "Alcoholic Beverage Manufacturing", approvalNeeded: true },
  { code: "3122", sector: "31-33 Manufacturing", description: "Tobacco Manufacturing", approvalNeeded: true },
  { code: "324", sector: "31-33 Manufacturing", description: "Petroleum and Coal Products Manufacturing", approvalNeeded: true },
  { code: "3254", sector: "31-33 Manufacturing", description: "Pharmaceutical and Medicine Manufacturing", approvalNeeded: true },
  { code: "3259", sector: "31-33 Manufacturing", description: "Other Chemical Product and Preparation Manufacturing", approvalNeeded: true },
  { code: "339A", sector: "31-33 Manufacturing", description: "Jewelry, Precious Stone, Precious Metal and Silverware Manufacturing", approvalNeeded: true },
  { code: "339C", sector: "31-33 Manufacturing", description: "Medical Equipment and Supplies Manufacturing", approvalNeeded: true },
  { code: "311", sector: "31-33 Manufacturing", description: "Food Manufacturing", approvalNeeded: false },
  { code: "311811", sector: "31-33 Manufacturing", description: "Bakeries", approvalNeeded: false },
  { code: "3121B", sector: "31-33 Manufacturing", description: "Non-Alcoholic Beverage Manufacturing", approvalNeeded: false },
  { code: "313", sector: "31-33 Manufacturing", description: "Textile Mills", approvalNeeded: false },
  { code: "314", sector: "31-33 Manufacturing", description: "Textile Product Mills", approvalNeeded: false },
  { code: "315", sector: "31-33 Manufacturing", description: "Apparel Manufacturing", approvalNeeded: false },
  { code: "316", sector: "31-33 Manufacturing", description: "Leather and Allied Product Manufacturing", approvalNeeded: false },
  { code: "321", sector: "31-33 Manufacturing", description: "Wood Product Manufacturing", approvalNeeded: false },
  { code: "322", sector: "31-33 Manufacturing", description: "Paper Manufacturing", approvalNeeded: false },
  { code: "323", sector: "31-33 Manufacturing", description: "Printing and Related Support Activities", approvalNeeded: false },
  { code: "323A", sector: "31-33 Manufacturing", description: "Typesetting, Plate Making and Related Services", approvalNeeded: false },
  { code: "3255", sector: "31-33 Manufacturing", description: "Paint, Coating, and Adhesive Manufacturing", approvalNeeded: false },
  { code: "326", sector: "31-33 Manufacturing", description: "Plastics and Rubber Products Manufacturing", approvalNeeded: false },
  { code: "327", sector: "31-33 Manufacturing", description: "Nonmetallic Mineral Product Manufacturing", approvalNeeded: false },
  { code: "331", sector: "31-33 Manufacturing", description: "Primary Metal Manufacturing", approvalNeeded: false },
  { code: "332", sector: "31-33 Manufacturing", description: "Fabricated Metal Product Manufacturing", approvalNeeded: false },
  { code: "333", sector: "31-33 Manufacturing", description: "Machinery Manufacturing", approvalNeeded: false },
  { code: "334", sector: "31-33 Manufacturing", description: "Computer and Electronic Product Manufacturing", approvalNeeded: false },
  { code: "335", sector: "31-33 Manufacturing", description: "Electrical Equipment, Appliance, and Component Manufacturing", approvalNeeded: false },
  { code: "336", sector: "31-33 Manufacturing", description: "Transportation (Equipment) Manufacturing", approvalNeeded: false },
  { code: "337", sector: "31-33 Manufacturing", description: "Furniture and Related Product Manufacturing", approvalNeeded: false },
  { code: "339D", sector: "31-33 Manufacturing", description: "Other Miscellaneous Durable Good Manufacturing", approvalNeeded: false },
  { code: "339E", sector: "31-33 Manufacturing", description: "Other Miscellaneous Nondurable Goods Manufacturing", approvalNeeded: false },
  { code: "42311", sector: "42 Wholesale Trade", description: "Automobile and Other Motor Vehicle Merchant Wholesalers", approvalNeeded: true },
  { code: "42312", sector: "42 Wholesale Trade", description: "Motor Vehicle Supplies and New Parts Merchant Wholesalers", approvalNeeded: true },
  { code: "42313", sector: "42 Wholesale Trade", description: "Tire and Tube Merchant Wholesalers", approvalNeeded: true },
  { code: "42314", sector: "42 Wholesale Trade", description: "Motor Vehicle Parts (Used) Merchant Wholesalers", approvalNeeded: true },
  { code: "42345", sector: "42 Wholesale Trade", description: "Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers", approvalNeeded: true },
  { code: "42394", sector: "42 Wholesale Trade", description: "Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers", approvalNeeded: true },
  { code: "4242", sector: "42 Wholesale Trade", description: "Drugs and Druggists' Sundries Merchant Wholesalers", approvalNeeded: true },
  { code: "4246", sector: "42 Wholesale Trade", description: "Chemical and Allied Products Merchant Wholesalers", approvalNeeded: true },
  { code: "4247", sector: "42 Wholesale Trade", description: "Petroleum and Petroleum Products Merchant Wholesalers", approvalNeeded: true },
  { code: "4248", sector: "42 Wholesale Trade", description: "Beer, Wine, and Distilled Alcoholic Beverage Merchant Wholesalers", approvalNeeded: true },
  { code: "42494", sector: "42 Wholesale Trade", description: "Tobacco and Tobacco Product Merchant Wholesalers", approvalNeeded: true },
  { code: "4232", sector: "42 Wholesale Trade", description: "Furniture and Home Furnishing Merchant Wholesalers", approvalNeeded: false },
  { code: "4233", sector: "42 Wholesale Trade", description: "Lumber and Other Construction Materials Merchant Wholesalers", approvalNeeded: false },
  { code: "42341", sector: "42 Wholesale Trade", description: "Photographic Equipment and Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "42342", sector: "42 Wholesale Trade", description: "Office Equipment Merchant Wholesalers (Office Furniture)", approvalNeeded: false },
  { code: "42342A", sector: "42 Wholesale Trade", description: "Office Equipment Merchant Wholesalers (Stationary)", approvalNeeded: false },
  { code: "42343", sector: "42 Wholesale Trade", description: "Computer and Computer Peripheral Equipment and Software Merchant Wholesalers", approvalNeeded: false },
  { code: "42344", sector: "42 Wholesale Trade", description: "Other Commercial Equipment Merchant Wholesalers", approvalNeeded: false },
  { code: "42349", sector: "42 Wholesale Trade", description: "Other Professional Equipment and Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "4235", sector: "42 Wholesale Trade", description: "Metal and Mineral (except Petroleum) Merchant Wholesalers", approvalNeeded: false },
  { code: "4236", sector: "42 Wholesale Trade", description: "Household Appliances and Electrical and Electronic Goods Merchant Wholesalers", approvalNeeded: false },
  { code: "4237", sector: "42 Wholesale Trade", description: "Hardware, Equipment and Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "4237A", sector: "42 Wholesale Trade", description: "Plumbing and Heating Equipment and Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "4238", sector: "42 Wholesale Trade", description: "Machinery, Equipment, and Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "42399", sector: "42 Wholesale Trade", description: "Other Miscellaneous Durable Goods Merchant Wholesalers", approvalNeeded: false },
  { code: "4241", sector: "42 Wholesale Trade", description: "Paper and Paper Product Merchant Wholesalers", approvalNeeded: false },
  { code: "4243", sector: "42 Wholesale Trade", description: "Apparel, Piece Goods, and Notions Merchant Wholesalers", approvalNeeded: false },
  { code: "4243A", sector: "42 Wholesale Trade", description: "Uniforms and Commercial Clothing Merchant Wholesalers", approvalNeeded: false },
  { code: "4243B", sector: "42 Wholesale Trade", description: "Commercial Footwear Merchant Wholesalers", approvalNeeded: false },
  { code: "4244", sector: "42 Wholesale Trade", description: "Grocery and Related Product Merchant Wholesalers", approvalNeeded: false },
  { code: "4245", sector: "42 Wholesale Trade", description: "Farm Product Raw Material Merchant Wholesalers", approvalNeeded: false },
  { code: "42491", sector: "42 Wholesale Trade", description: "Farm Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "42492", sector: "42 Wholesale Trade", description: "Book, Periodical, and Newspaper Merchant Wholesalers", approvalNeeded: false },
  { code: "42493", sector: "42 Wholesale Trade", description: "Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "42495", sector: "42 Wholesale Trade", description: "Paint, Varnish, and Supplies Merchant Wholesalers", approvalNeeded: false },
  { code: "42499", sector: "42 Wholesale Trade", description: "Other Miscellaneous Nondurable Goods Merchant Wholesalers", approvalNeeded: false },
  { code: "42511", sector: "42 Wholesale Trade", description: "Business to Business Electronic Markets", approvalNeeded: false },
  { code: "42512", sector: "42 Wholesale Trade", description: "Wholesale Trade Agents and Brokers", approvalNeeded: false },
  { code: "4251A", sector: "42 Wholesale Trade", description: "Intra-Company Purchases", approvalNeeded: false },
  { code: "44111", sector: "44-45 Retail Trade", description: "New Car Dealers", approvalNeeded: true },
  { code: "44112", sector: "44-45 Retail Trade", description: "Used Car Dealers", approvalNeeded: true },
  { code: "4411B", sector: "44-45 Retail Trade", description: "Used Car Dealers - Reputable", approvalNeeded: true },
  { code: "44121", sector: "44-45 Retail Trade", description: "Recreational Vehicle Dealers", approvalNeeded: true },
  { code: "441222", sector: "44-45 Retail Trade", description: "Boat Dealers", approvalNeeded: true },
  { code: "441228", sector: "44-45 Retail Trade", description: "Motorcycle, ATV, and All Other Motor Vehicle Dealers", approvalNeeded: true },
  { code: "44122A", sector: "44-45 Retail Trade", description: "Snowmobile Dealers", approvalNeeded: true },
  { code: "44122B", sector: "44-45 Retail Trade", description: "Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers", approvalNeeded: true },
  { code: "4412A", sector: "44-45 Retail Trade", description: "Mobile Home Dealers", approvalNeeded: true },
  { code: "4412B", sector: "44-45 Retail Trade", description: "Utility Trailer Dealers", approvalNeeded: true },
  { code: "44131", sector: "44-45 Retail Trade", description: "Automotive Parts and Accessories Stores", approvalNeeded: true },
  { code: "44132", sector: "44-45 Retail Trade", description: "Tire Dealers", approvalNeeded: true },
  { code: "4453", sector: "44-45 Retail Trade", description: "Beer, Wine, and Liquor Stores", approvalNeeded: true },
  { code: "44611", sector: "44-45 Retail Trade", description: "Pharmacies and Drug Stores", approvalNeeded: true },
  { code: "44613", sector: "44-45 Retail Trade", description: "Optical Goods Stores", approvalNeeded: true },
  { code: "446191", sector: "44-45 Retail Trade", description: "Food (Health) Supplement Stores (Nutraceuticals, Food)", approvalNeeded: true },
  { code: "44619A", sector: "44-45 Retail Trade", description: "Food (Health) Supplement Stores (Nutraceuticals, Food) - Regulated", approvalNeeded: true },
  { code: "4461A", sector: "44-45 Retail Trade", description: "Nutraceutical Stores (Non-Food)", approvalNeeded: true },
  { code: "4461B", sector: "44-45 Retail Trade", description: "Nutraceuticals Stores (Non-Food) - Regulated", approvalNeeded: true },
  { code: "4461C", sector: "44-45 Retail Trade", description: "Cannabis Stores", approvalNeeded: true },
  { code: "4481C", sector: "44-45 Retail Trade", description: "Men's Clothing Stores - High Value", approvalNeeded: true },
  { code: "4481D", sector: "44-45 Retail Trade", description: "Men's and Women's Clothing Stores - High Value", approvalNeeded: true },
  { code: "4481E", sector: "44-45 Retail Trade", description: "Children's and Infants' Clothing Stores - High Value", approvalNeeded: true },
  { code: "4481F", sector: "44-45 Retail Trade", description: "Women's Clothing Stores - High Value", approvalNeeded: true },
  { code: "4481G", sector: "44-45 Retail Trade", description: "Other Clothing (Accessories) Stores - High Value", approvalNeeded: true },
  { code: "44831", sector: "44-45 Retail Trade", description: "Jewelry Stores", approvalNeeded: true },
  { code: "4483B", sector: "44-45 Retail Trade", description: "Luggage and Leather Goods Stores - High Value", approvalNeeded: true },
  { code: "4523B", sector: "44-45 Retail Trade", description: "Marketplaces", approvalNeeded: true },
  { code: "45392", sector: "44-45 Retail Trade", description: "Art Dealers", approvalNeeded: true },
  { code: "453991", sector: "44-45 Retail Trade", description: "Tobacco Stores", approvalNeeded: true },
  { code: "4539D", sector: "44-45 Retail Trade", description: "Auction Houses", approvalNeeded: true },
  { code: "4539G", sector: "44-45 Retail Trade", description: "Adult Goods", approvalNeeded: true },
  { code: "45431", sector: "44-45 Retail Trade", description: "Fuel Dealers", approvalNeeded: true },
  { code: "442A", sector: "44-45 Retail Trade", description: "Furniture Stores", approvalNeeded: false },
  { code: "442B", sector: "44-45 Retail Trade", description: "Home Furnishings Stores (Miscellaneous)", approvalNeeded: false },
  { code: "442C", sector: "44-45 Retail Trade", description: "Home Furnishings Stores (Floor Covering Stores)", approvalNeeded: false },
  { code: "442D", sector: "44-45 Retail Trade", description: "Home Furnishings Stores (Drapery and Upholstery Stores)", approvalNeeded: false },
  { code: "442E", sector: "44-45 Retail Trade", description: "Home Furnishings Stores (Fireplace and Accessories Stores)", approvalNeeded: false },
  { code: "442F", sector: "44-45 Retail Trade", description: "Glassware/Crystal Stores", approvalNeeded: false },
  { code: "443141", sector: "44-45 Retail Trade", description: "Household Appliance Stores", approvalNeeded: false },
  { code: "443142", sector: "44-45 Retail Trade", description: "Electronics Stores", approvalNeeded: false },
  { code: "4431A", sector: "44-45 Retail Trade", description: "Computer Software Stores", approvalNeeded: false },
  { code: "4431B", sector: "44-45 Retail Trade", description: "Telecommunication Equipment and Telephone Stores", approvalNeeded: false },
  { code: "44411", sector: "44-45 Retail Trade", description: "Home Centers", approvalNeeded: false },
  { code: "44412", sector: "44-45 Retail Trade", description: "Paint and Wallpaper Stores", approvalNeeded: false },
  { code: "44413", sector: "44-45 Retail Trade", description: "Hardware Stores", approvalNeeded: false },
  { code: "44419", sector: "44-45 Retail Trade", description: "Other Building Material Stores", approvalNeeded: false },
  { code: "4441A", sector: "44-45 Retail Trade", description: "Lawn and Garden Supplies Stores", approvalNeeded: false },
  { code: "4451", sector: "44-45 Retail Trade", description: "Grocery Stores, Supermarkets", approvalNeeded: false },
  { code: "4452", sector: "44-45 Retail Trade", description: "Specialty Food Stores", approvalNeeded: false },
  { code: "4452A", sector: "44-45 Retail Trade", description: "Freezer and Locker Meat Provisioners", approvalNeeded: false },
  { code: "4452B", sector: "44-45 Retail Trade", description: "Candy, Nut, and Confectionery Stores", approvalNeeded: false },
  { code: "4452C", sector: "44-45 Retail Trade", description: "Dairy Products Stores", approvalNeeded: false },
  { code: "44612", sector: "44-45 Retail Trade", description: "Cosmetics, Beauty Supplies, and Perfume Stores", approvalNeeded: false },
  { code: "446199", sector: "44-45 Retail Trade", description: "All Other Health and Personal Care Stores", approvalNeeded: false },
  { code: "44619C", sector: "44-45 Retail Trade", description: "Orthopedic Goods Stores", approvalNeeded: false },
  { code: "44619D", sector: "44-45 Retail Trade", description: "Electric Razor Stores", approvalNeeded: false },
  { code: "44619E", sector: "44-45 Retail Trade", description: "Hearing Aids Stores", approvalNeeded: false },
  { code: "447", sector: "44-45 Retail Trade", description: "Gasoline Stations", approvalNeeded: false },
  { code: "447A", sector: "44-45 Retail Trade", description: "Automated Fuel Dispensers", approvalNeeded: false },
  { code: "44811", sector: "44-45 Retail Trade", description: "Men's Clothing Stores", approvalNeeded: false },
  { code: "44812", sector: "44-45 Retail Trade", description: "Women's Clothing Stores", approvalNeeded: false },
  { code: "44812A", sector: "44-45 Retail Trade", description: "Women\u2019s Accessory and Specialty Shops", approvalNeeded: false },
  { code: "44813", sector: "44-45 Retail Trade", description: "Children's and Infants' Clothing Stores", approvalNeeded: false },
  { code: "44814", sector: "44-45 Retail Trade", description: "Family Clothing Stores", approvalNeeded: false },
  { code: "44819", sector: "44-45 Retail Trade", description: "Other Clothing (Accessories) Stores", approvalNeeded: false },
  { code: "44819B", sector: "44-45 Retail Trade", description: "Tailors, Seamstresses, Mending, and Alterations", approvalNeeded: false },
  { code: "44819C", sector: "44-45 Retail Trade", description: "Wig and Toupee Stores", approvalNeeded: false },
  { code: "4481A", sector: "44-45 Retail Trade", description: "Men's and Women's Clothing Stores", approvalNeeded: false },
  { code: "4481B", sector: "44-45 Retail Trade", description: "Sports Apparel, Riding Apparel Stores", approvalNeeded: false },
  { code: "4482", sector: "44-45 Retail Trade", description: "Shoe Stores", approvalNeeded: false },
  { code: "44832", sector: "44-45 Retail Trade", description: "Luggage and Leather Goods Stores", approvalNeeded: false },
  { code: "44832A", sector: "44-45 Retail Trade", description: "Furriers and Fur Shops", approvalNeeded: false },
  { code: "45111", sector: "44-45 Retail Trade", description: "Sporting Goods Stores", approvalNeeded: false },
  { code: "45112", sector: "44-45 Retail Trade", description: "Hobby, Toy, and Game Stores", approvalNeeded: false },
  { code: "45113", sector: "44-45 Retail Trade", description: "Sewing, Needlework, and Piece Goods Stores", approvalNeeded: false },
  { code: "45114", sector: "44-45 Retail Trade", description: "Musical Instrument and Supplies Stores", approvalNeeded: false },
  { code: "4511B", sector: "44-45 Retail Trade", description: "Bicycle Stores", approvalNeeded: false },
  { code: "4512", sector: "44-45 Retail Trade", description: "Book Stores", approvalNeeded: false },
  { code: "4522", sector: "44-45 Retail Trade", description: "Department Stores", approvalNeeded: false },
  { code: "4523", sector: "44-45 Retail Trade", description: "General Merchandise Stores, including Warehouse Clubs and Supercenters", approvalNeeded: false },
  { code: "4523A", sector: "44-45 Retail Trade", description: "Wholesale Clubs", approvalNeeded: false },
  { code: "452A", sector: "44-45 Retail Trade", description: "Buying and Shopping Services and Clubs", approvalNeeded: false },
  { code: "4531", sector: "44-45 Retail Trade", description: "Florists", approvalNeeded: false },
  { code: "45321", sector: "44-45 Retail Trade", description: "Office Supplies and Stationery Stores", approvalNeeded: false },
  { code: "45322", sector: "44-45 Retail Trade", description: "Gift, Novelty, and Souvenir Stores", approvalNeeded: false },
  { code: "4533", sector: "44-45 Retail Trade", description: "Used Merchandise Stores", approvalNeeded: false },
  { code: "45391", sector: "44-45 Retail Trade", description: "Pet and Pet Supplies Stores", approvalNeeded: false },
  { code: "453998", sector: "44-45 Retail Trade", description: "All Other Miscellaneous Store Retailers", approvalNeeded: false },
  { code: "45399A", sector: "44-45 Retail Trade", description: "Variety Stores", approvalNeeded: false },
  { code: "45399B", sector: "44-45 Retail Trade", description: "Record Stores", approvalNeeded: false },
  { code: "45399C", sector: "44-45 Retail Trade", description: "Camera and Photographic Supply Stores", approvalNeeded: false },
  { code: "45399D", sector: "44-45 Retail Trade", description: "Artists Supply and Craft Shops", approvalNeeded: false },
  { code: "45399E", sector: "44-45 Retail Trade", description: "Religious Goods Stores", approvalNeeded: false },
  { code: "45399F", sector: "44-45 Retail Trade", description: "Typewriter Stores", approvalNeeded: false },
  { code: "45399G", sector: "44-45 Retail Trade", description: "Swimming Pools Stores", approvalNeeded: false },
  { code: "45399H", sector: "44-45 Retail Trade", description: "Tent and Awning Stores", approvalNeeded: false },
  { code: "4539B", sector: "44-45 Retail Trade", description: "Stamp and Coin Stores", approvalNeeded: false },
  { code: "4539H", sector: "44-45 Retail Trade", description: "Discount Stores", approvalNeeded: false },
  { code: "4539I", sector: "44-45 Retail Trade", description: "Duty Free Stores", approvalNeeded: false },
  { code: "4539J", sector: "44-45 Retail Trade", description: "Second Hand Stores", approvalNeeded: false },
  { code: "4539K", sector: "44-45 Retail Trade", description: "Antique Stores", approvalNeeded: false },
  { code: "4539L", sector: "44-45 Retail Trade", description: "Antique Reproductions", approvalNeeded: false },
  { code: "4542A", sector: "44-45 Retail Trade", description: "Vending Machines (Food)", approvalNeeded: false },
  { code: "4542B", sector: "44-45 Retail Trade", description: "Vending Machines (Non-Food)", approvalNeeded: false },
  { code: "481A", sector: "48-49 Transportation and Warehousing", description: "Passenger Air Transportation", approvalNeeded: true },
  { code: "481HN", sector: "48-49 Transportation and Warehousing", description: "Other Air Transportation", approvalNeeded: true },
  { code: "483A", sector: "48-49 Transportation and Warehousing", description: "Cruise Lines", approvalNeeded: true },
  { code: "482A", sector: "48-49 Transportation and Warehousing", description: "Passenger Rail Transportation", approvalNeeded: false },
  { code: "482B", sector: "48-49 Transportation and Warehousing", description: "Freight Rail Transportation", approvalNeeded: false },
  { code: "483B", sector: "48-49 Transportation and Warehousing", description: "Ferries", approvalNeeded: false },
  { code: "483C", sector: "48-49 Transportation and Warehousing", description: "Water Freight", approvalNeeded: false },
  { code: "484", sector: "48-49 Transportation and Warehousing", description: "Truck Transportation", approvalNeeded: false },
  { code: "4851", sector: "48-49 Transportation and Warehousing", description: "Urban Transit Systems", approvalNeeded: false },
  { code: "4852", sector: "48-49 Transportation and Warehousing", description: "Interurban and Rural Bus Transportation", approvalNeeded: false },
  { code: "4853", sector: "48-49 Transportation and Warehousing", description: "Taxi and Limousine Service", approvalNeeded: false },
  { code: "4854", sector: "48-49 Transportation and Warehousing", description: "School and Employee Bus Transportation", approvalNeeded: false },
  { code: "4855", sector: "48-49 Transportation and Warehousing", description: "Charter Bus Industry", approvalNeeded: false },
  { code: "4859", sector: "48-49 Transportation and Warehousing", description: "Other Transit and Ground Passenger Transportation", approvalNeeded: false },
  { code: "487", sector: "48-49 Transportation and Warehousing", description: "Scenic and Sightseeing Transportation", approvalNeeded: false },
  { code: "48819", sector: "48-49 Transportation and Warehousing", description: "Other Support Activities for Air Transportation", approvalNeeded: false },
  { code: "4881A", sector: "48-49 Transportation and Warehousing", description: "Airports, Airport Terminals, Flying Fields", approvalNeeded: false },
  { code: "4882", sector: "48-49 Transportation and Warehousing", description: "Support Activities for Rail Transportation", approvalNeeded: false },
  { code: "4883", sector: "48-49 Transportation and Warehousing", description: "Support Activities for Water Transportation", approvalNeeded: false },
  { code: "48841", sector: "48-49 Transportation and Warehousing", description: "Motor Vehicle Towing", approvalNeeded: false },
  { code: "48849", sector: "48-49 Transportation and Warehousing", description: "Other Support Activities for Road Transportation", approvalNeeded: false },
  { code: "4884A", sector: "48-49 Transportation and Warehousing", description: "Bridge and Road Fees, Tolls", approvalNeeded: false },
  { code: "4884B", sector: "48-49 Transportation and Warehousing", description: "Electric Vehicle Charging", approvalNeeded: false },
  { code: "4889", sector: "48-49 Transportation and Warehousing", description: "Other Support Activities for Transportation", approvalNeeded: false },
  { code: "491", sector: "48-49 Transportation and Warehousing", description: "Postal Service", approvalNeeded: false },
  { code: "492", sector: "48-49 Transportation and Warehousing", description: "Couriers and Messengers", approvalNeeded: false },
  { code: "493", sector: "48-49 Transportation and Warehousing", description: "Warehousing and Storage", approvalNeeded: false },
  { code: "5112D", sector: "51 Information", description: "Digital Goods - Streaming Services", approvalNeeded: true },
  { code: "5112I", sector: "51 Information", description: "Digital Goods - Games (in-game items)", approvalNeeded: true },
  { code: "517311", sector: "51 Information", description: "Wired Telecommunications Carriers", approvalNeeded: true },
  { code: "518A", sector: "51 Information", description: "Cloud Storage Services", approvalNeeded: true },
  { code: "518B", sector: "51 Information", description: "Domain Hosting Services", approvalNeeded: true },
  { code: "518C", sector: "51 Information", description: "VPN Services", approvalNeeded: true },
  { code: "518D", sector: "51 Information", description: "File Sharing Services", approvalNeeded: true },
  { code: "518E", sector: "51 Information", description: "Cyber Lockers Services", approvalNeeded: true },
  { code: "5111", sector: "51 Information", description: "Newspaper, Periodical, Book, and Directory Publishers (except Internet)", approvalNeeded: false },
  { code: "51121", sector: "51 Information", description: "Digital Goods - Software Applications", approvalNeeded: false },
  { code: "5112A", sector: "51 Information", description: "Digital Goods - Audiovisual Media Including Books, Movies, and Music", approvalNeeded: false },
  { code: "5112B", sector: "51 Information", description: "Digital Goods - Games", approvalNeeded: false },
  { code: "5112H", sector: "51 Information", description: "Digital Goods - Large Digital Goods Merchant (V) Digital Goods: Multi-Category (M)", approvalNeeded: false },
  { code: "51211", sector: "51 Information", description: "Motion Picture and Video Production", approvalNeeded: false },
  { code: "51212", sector: "51 Information", description: "Motion Picture and Video Distribution", approvalNeeded: false },
  { code: "51213", sector: "51 Information", description: "Motion Picture and Video Exhibition", approvalNeeded: false },
  { code: "5122", sector: "51 Information", description: "Sound Recording Industries", approvalNeeded: false },
  { code: "515", sector: "51 Information", description: "Broadcasting (except Internet)", approvalNeeded: false },
  { code: "51731B", sector: "51 Information", description: "Wireless Telecommunications Carriers - Prepaid", approvalNeeded: false },
  { code: "51731D", sector: "51 Information", description: "Other Wireless Telecommunications Carriers", approvalNeeded: false },
  { code: "5179", sector: "51 Information", description: "Other Telecommunications", approvalNeeded: false },
  { code: "517911", sector: "51 Information", description: "Telecommunications Resellers", approvalNeeded: false },
  { code: "51911", sector: "51 Information", description: "News Agency", approvalNeeded: false },
  { code: "51913", sector: "51 Information", description: "Internet Publishing and Broadcasting and Web Search Portals", approvalNeeded: false },
  { code: "5191A", sector: "51 Information", description: "All Other Information Services", approvalNeeded: false },
  { code: "52231", sector: "52 Finance and Insurance", description: "Mortgage and Non-mortgage Loan Brokers", approvalNeeded: true },
  { code: "524114", sector: "52 Finance and Insurance", description: "Direct Health and Medical Insurance Carriers", approvalNeeded: true },
  { code: "52412", sector: "52 Finance and Insurance", description: "Direct Insurance (except Life, Health, and Medical) Carriers", approvalNeeded: true },
  { code: "52413", sector: "52 Finance and Insurance", description: "Reinsurance Carriers", approvalNeeded: true },
  { code: "5242", sector: "52 Finance and Insurance", description: "Agencies, Brokerages, and Other Insurance Related Activities", approvalNeeded: true },
  { code: "5311", sector: "53 Real Estate and Rental and Leasing", description: "Lessors of Real Estate", approvalNeeded: true },
  { code: "5312", sector: "53 Real Estate and Rental and Leasing", description: "Offices of Real Estate Agents and Brokers", approvalNeeded: true },
  { code: "5313", sector: "53 Real Estate and Rental and Leasing", description: "Activities Related to Real Estate", approvalNeeded: true },
  { code: "53211", sector: "53 Real Estate and Rental and Leasing", description: "Passenger Car Rental and Leasing", approvalNeeded: false },
  { code: "53212", sector: "53 Real Estate and Rental and Leasing", description: "Truck, Utility Trailer Rental and Leasing", approvalNeeded: false },
  { code: "5321B", sector: "53 Real Estate and Rental and Leasing", description: "Motor Home and Recreational Vehicle Rentals", approvalNeeded: false },
  { code: "53221", sector: "53 Real Estate and Rental and Leasing", description: "Consumer Electronics and Appliances Rental", approvalNeeded: false },
  { code: "532281", sector: "53 Real Estate and Rental and Leasing", description: "Formal Wear and Costume Rental", approvalNeeded: false },
  { code: "532282", sector: "53 Real Estate and Rental and Leasing", description: "Video Tape and Disc Rental", approvalNeeded: false },
  { code: "532283", sector: "53 Real Estate and Rental and Leasing", description: "Home Health Equipment Rental", approvalNeeded: false },
  { code: "532284", sector: "53 Real Estate and Rental and Leasing", description: "Recreational Goods Rental", approvalNeeded: false },
  { code: "532289", sector: "53 Real Estate and Rental and Leasing", description: "All Other Consumer Goods Rental", approvalNeeded: false },
  { code: "5324", sector: "53 Real Estate and Rental and Leasing", description: "Commercial and Industrial Machinery and Equipment Rental and Leasing", approvalNeeded: false },
  { code: "5417A", sector: "54 Professional, Scientific, and Technical Services", description: "Ancestry Research", approvalNeeded: true },
  { code: "5411A", sector: "54 Professional, Scientific, and Technical Services", description: "Lawyers (except Bankruptcy)", approvalNeeded: false },
  { code: "541211", sector: "54 Professional, Scientific, and Technical Services", description: "Offices of Certified Public Accountants", approvalNeeded: false },
  { code: "541213", sector: "54 Professional, Scientific, and Technical Services", description: "Tax Preparation Services", approvalNeeded: false },
  { code: "5413", sector: "54 Professional, Scientific, and Technical Services", description: "Architectural, Engineering, and Related Services", approvalNeeded: false },
  { code: "5414", sector: "54 Professional, Scientific, and Technical Services", description: "Specialized Design Services", approvalNeeded: false },
  { code: "5415", sector: "54 Professional, Scientific, and Technical Services", description: "Computer Systems Design and Related Services", approvalNeeded: false },
  { code: "5416", sector: "54 Professional, Scientific, and Technical Services", description: "Management, Scientific, and Technical Consulting Services", approvalNeeded: false },
  { code: "54171", sector: "54 Professional, Scientific, and Technical Services", description: "Research and Development in the Physical, Engineering, and Life Sciences", approvalNeeded: false },
  { code: "5417B", sector: "54 Professional, Scientific, and Technical Services", description: "Other Research and Development in the Social Sciences and Humanities", approvalNeeded: false },
  { code: "5418", sector: "54 Professional, Scientific, and Technical Services", description: "Advertising, Public Relations, and Related Services", approvalNeeded: false },
  { code: "54192", sector: "54 Professional, Scientific, and Technical Services", description: "Photographic Services", approvalNeeded: false },
  { code: "54194", sector: "54 Professional, Scientific, and Technical Services", description: "Veterinary Services", approvalNeeded: false },
  { code: "54199", sector: "54 Professional, Scientific, and Technical Services", description: "All Other Professional, Scientific, and Technical Services", approvalNeeded: false },
  { code: "54199A", sector: "54 Professional, Scientific, and Technical Services", description: "Testing Laboratories (Non-Medical Testing)", approvalNeeded: false },
  { code: "55", sector: "55 Management of Companies and Enterprises", description: "Management of Companies and Enterprises", approvalNeeded: false },
  { code: "56145", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Credit Bureaus", approvalNeeded: true },
  { code: "5615", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Travel Arrangement and Reservation Services", approvalNeeded: true },
  { code: "5611", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Office Administrative Services", approvalNeeded: false },
  { code: "5612", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Facilities Support Services", approvalNeeded: false },
  { code: "5613", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Employment Services", approvalNeeded: false },
  { code: "56141", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Document Preparation Services (Photocopy Services)", approvalNeeded: false },
  { code: "56141A", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Document Preparation Services (Secretarial Services)", approvalNeeded: false },
  { code: "56142", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Telephone Call Centers", approvalNeeded: false },
  { code: "56143", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Business Service Centers", approvalNeeded: false },
  { code: "56149", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Other Business Support Services", approvalNeeded: false },
  { code: "5616A", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Security Services", approvalNeeded: false },
  { code: "56171", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Exterminating and Pest Control Services", approvalNeeded: false },
  { code: "56172", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Janitorial Services", approvalNeeded: false },
  { code: "56172A", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Specialty Cleaning", approvalNeeded: false },
  { code: "56173", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Landscaping Services", approvalNeeded: false },
  { code: "56174", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Carpet and Upholstery Cleaning Services", approvalNeeded: false },
  { code: "56179", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Other Services to Buildings and Dwellings", approvalNeeded: false },
  { code: "5619", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Other Support Services", approvalNeeded: false },
  { code: "562", sector: "56 Administrative and Support and Waste Management and Remediation Services", description: "Waste Management and Remediation Services", approvalNeeded: false },
  { code: "6111", sector: "61 Educational Services", description: "Elementary and Secondary Schools", approvalNeeded: false },
  { code: "6112", sector: "61 Educational Services", description: "Junior Colleges", approvalNeeded: false },
  { code: "6113", sector: "61 Educational Services", description: "Colleges, Universities, and Professional Schools", approvalNeeded: false },
  { code: "6114", sector: "61 Educational Services", description: "Business Schools and Computer and Management Training", approvalNeeded: false },
  { code: "6115", sector: "61 Educational Services", description: "Technical and Trade Schools", approvalNeeded: false },
  { code: "61161", sector: "61 Educational Services", description: "Fine Arts Schools", approvalNeeded: false },
  { code: "61162", sector: "61 Educational Services", description: "Sports and Recreation Instruction", approvalNeeded: false },
  { code: "61163", sector: "61 Educational Services", description: "Language Schools", approvalNeeded: false },
  { code: "61169", sector: "61 Educational Services", description: "All Other Schools and Instruction", approvalNeeded: false },
  { code: "61169A", sector: "61 Educational Services", description: "Correspondence Schools", approvalNeeded: false },
  { code: "6116A", sector: "61 Educational Services", description: "Dance Schools", approvalNeeded: false },
  { code: "6211", sector: "62 Health Care and Social Assistance", description: "Offices of Physicians", approvalNeeded: true },
  { code: "6212", sector: "62 Health Care and Social Assistance", description: "Offices of Dentists", approvalNeeded: true },
  { code: "62131", sector: "62 Health Care and Social Assistance", description: "Offices of Chiropractors", approvalNeeded: true },
  { code: "62132", sector: "62 Health Care and Social Assistance", description: "Offices of Optometrists", approvalNeeded: true },
  { code: "62133", sector: "62 Health Care and Social Assistance", description: "Offices of Mental Health Practitioners", approvalNeeded: true },
  { code: "62134", sector: "62 Health Care and Social Assistance", description: "Offices of Physical, Occupational and Speech Therapists, and Audiologists", approvalNeeded: true },
  { code: "62139", sector: "62 Health Care and Social Assistance", description: "Offices of All Other Health Practitioners", approvalNeeded: true },
  { code: "62139A", sector: "62 Health Care and Social Assistance", description: "Osteopaths", approvalNeeded: true },
  { code: "62139B", sector: "62 Health Care and Social Assistance", description: "Podiatrists and Chiropodists", approvalNeeded: true },
  { code: "6214", sector: "62 Health Care and Social Assistance", description: "Outpatient Care Centers", approvalNeeded: true },
  { code: "6215", sector: "62 Health Care and Social Assistance", description: "Medical and Diagnostic Laboratories", approvalNeeded: true },
  { code: "6216", sector: "62 Health Care and Social Assistance", description: "Home Health Care Services", approvalNeeded: true },
  { code: "621A", sector: "62 Health Care and Social Assistance", description: "Commercial Private Health and e-doctor Services", approvalNeeded: true },
  { code: "622", sector: "62 Health Care and Social Assistance", description: "Hospitals", approvalNeeded: true },
  { code: "623", sector: "62 Health Care and Social Assistance", description: "Nursing and Residential Care Facilities", approvalNeeded: true },
  { code: "6219", sector: "62 Health Care and Social Assistance", description: "Other Ambulatory Health Care Services", approvalNeeded: false },
  { code: "6219A", sector: "62 Health Care and Social Assistance", description: "Ambulance Services", approvalNeeded: false },
  { code: "6241", sector: "62 Health Care and Social Assistance", description: "Individual and Family Services", approvalNeeded: false },
  { code: "6242", sector: "62 Health Care and Social Assistance", description: "Community Food and Housing, and Emergency and Other Relief Services", approvalNeeded: false },
  { code: "6243", sector: "62 Health Care and Social Assistance", description: "Vocational Rehabilitation Services", approvalNeeded: false },
  { code: "6244", sector: "62 Health Care and Social Assistance", description: "Child Day Care Services", approvalNeeded: false },
  { code: "624A", sector: "62 Health Care and Social Assistance", description: "All Other Social Services", approvalNeeded: false },
  { code: "711A", sector: "71 Arts, Entertainment, and Recreation", description: "Ticketing Agencies", approvalNeeded: true },
  { code: "7111", sector: "71 Arts, Entertainment, and Recreation", description: "Performing Arts Companies", approvalNeeded: false },
  { code: "7112", sector: "71 Arts, Entertainment, and Recreation", description: "Spectator Sports", approvalNeeded: false },
  { code: "7113", sector: "71 Arts, Entertainment, and Recreation", description: "Promoters of Performing Arts, Sports, and Similar Events", approvalNeeded: false },
  { code: "7114", sector: "71 Arts, Entertainment, and Recreation", description: "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures", approvalNeeded: false },
  { code: "7115", sector: "71 Arts, Entertainment, and Recreation", description: "Independent Artists, Writers, and Performers", approvalNeeded: false },
  { code: "712", sector: "71 Arts, Entertainment, and Recreation", description: "Museums, Historical Sites, and Similar Institutions", approvalNeeded: false },
  { code: "71311", sector: "71 Arts, Entertainment, and Recreation", description: "Amusement and Theme Parks", approvalNeeded: false },
  { code: "71312", sector: "71 Arts, Entertainment, and Recreation", description: "Amusement Arcades (Establishments)", approvalNeeded: false },
  { code: "7131A", sector: "71 Arts, Entertainment, and Recreation", description: "Amusement Arcades (Supplies)", approvalNeeded: false },
  { code: "71392", sector: "71 Arts, Entertainment, and Recreation", description: "Skiing Facilities", approvalNeeded: false },
  { code: "71393", sector: "71 Arts, Entertainment, and Recreation", description: "Marinas", approvalNeeded: false },
  { code: "71394", sector: "71 Arts, Entertainment, and Recreation", description: "Fitness and Recreational Sports Centers", approvalNeeded: false },
  { code: "71395", sector: "71 Arts, Entertainment, and Recreation", description: "Bowling Centers", approvalNeeded: false },
  { code: "7139A", sector: "71 Arts, Entertainment, and Recreation", description: "Public Golf Courses", approvalNeeded: false },
  { code: "7139B", sector: "71 Arts, Entertainment, and Recreation", description: "Private Golf Courses and Country Clubs", approvalNeeded: false },
  { code: "7139C", sector: "71 Arts, Entertainment, and Recreation", description: "All Other Amusement and Recreation Industries", approvalNeeded: false },
  { code: "7139D", sector: "71 Arts, Entertainment, and Recreation", description: "Billiard and Pool Establishments", approvalNeeded: false },
  { code: "7139E", sector: "71 Arts, Entertainment, and Recreation", description: "Aquariums, Seaquariums, Dolphinariums, and Zoos", approvalNeeded: false },
  { code: "7211A", sector: "72 Accommodation and Food Services", description: "Timeshares", approvalNeeded: true },
  { code: "7224", sector: "72 Accommodation and Food Services", description: "Drinking Places (Alcoholic Beverages)", approvalNeeded: true },
  { code: "72111", sector: "72 Accommodation and Food Services", description: "Hotels (except Casino Hotels) and Motels", approvalNeeded: false },
  { code: "7211B", sector: "72 Accommodation and Food Services", description: "Other Traveler Accommodation", approvalNeeded: false },
  { code: "7212", sector: "72 Accommodation and Food Services", description: "Sporting and Recreational Camps", approvalNeeded: false },
  { code: "7212A", sector: "72 Accommodation and Food Services", description: "Recreational Vehicle Parks", approvalNeeded: false },
  { code: "7213", sector: "72 Accommodation and Food Services", description: "Rooming and Boarding Houses, Dormitories, and Workers' Camps", approvalNeeded: false },
  { code: "7223", sector: "72 Accommodation and Food Services", description: "Special Food Services", approvalNeeded: false },
  { code: "722511", sector: "72 Accommodation and Food Services", description: "Full-Service Restaurants (Restaurants)", approvalNeeded: false },
  { code: "722513", sector: "72 Accommodation and Food Services", description: "Limited-Service Restaurants (Fast Food Restaurants)", approvalNeeded: false },
  { code: "722514", sector: "72 Accommodation and Food Services", description: "Cafeterias, Grill Buffets, and Buffets", approvalNeeded: false },
  { code: "722515", sector: "72 Accommodation and Food Services", description: "Snack and Nonalcoholic Beverage Bars", approvalNeeded: false },
  { code: "8121C", sector: "81 Other Services (except Public Administration)", description: "Medical Spas", approvalNeeded: true },
  { code: "8129A", sector: "81 Other Services (except Public Administration)", description: "Dating Services (Casual)", approvalNeeded: true },
  { code: "8129C", sector: "81 Other Services (except Public Administration)", description: "Pseudo Science Services (Astrology, Psychokinesis, Clairvoyance, Fortune Telling, etc.)", approvalNeeded: true },
  { code: "8129F", sector: "81 Other Services (except Public Administration)", description: "Tipping Services", approvalNeeded: true },
  { code: "8131", sector: "81 Other Services (except Public Administration)", description: "Religious Organizations", approvalNeeded: true },
  { code: "813212", sector: "81 Other Services (except Public Administration)", description: "Voluntary Health Organizations", approvalNeeded: true },
  { code: "81321F", sector: "81 Other Services (except Public Administration)", description: "Other Grantmaking and Giving Services - Donation", approvalNeeded: true },
  { code: "813311", sector: "81 Other Services (except Public Administration)", description: "Human Rights Organizations", approvalNeeded: true },
  { code: "813312", sector: "81 Other Services (except Public Administration)", description: "Environment, Conservation and Wildlife Organizations", approvalNeeded: true },
  { code: "813319", sector: "81 Other Services (except Public Administration)", description: "Other Social Advocacy Organizations", approvalNeeded: true },
  { code: "81394", sector: "81 Other Services (except Public Administration)", description: "Political Organizations", approvalNeeded: true },
  { code: "8111", sector: "81 Other Services (except Public Administration)", description: "Automotive Repair and Maintenance", approvalNeeded: false },
  { code: "8111A", sector: "81 Other Services (except Public Administration)", description: "Automotive Body Repair Shops", approvalNeeded: false },
  { code: "8111B", sector: "81 Other Services (except Public Administration)", description: "Tire Retreading and Repair Shops", approvalNeeded: false },
  { code: "8111C", sector: "81 Other Services (except Public Administration)", description: "Automotive Paint Shops", approvalNeeded: false },
  { code: "8111E", sector: "81 Other Services (except Public Administration)", description: "Car Washes", approvalNeeded: false },
  { code: "8112", sector: "81 Other Services (except Public Administration)", description: "Electronic and Precision Equipment Repair and Maintenance (including Computers)", approvalNeeded: false },
  { code: "8112A", sector: "81 Other Services (except Public Administration)", description: "Computer Maintenance, Repair and Services (Not Elsewhere Classified)", approvalNeeded: false },
  { code: "8112B", sector: "81 Other Services (except Public Administration)", description: "Electrical and Small Appliance Repair Shops", approvalNeeded: false },
  { code: "8113", sector: "81 Other Services (except Public Administration)", description: "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance", approvalNeeded: false },
  { code: "8113A", sector: "81 Other Services (except Public Administration)", description: "Welding Services", approvalNeeded: false },
  { code: "8114", sector: "81 Other Services (except Public Administration)", description: "Personal and Household Goods Repair and Maintenance", approvalNeeded: false },
  { code: "8114A", sector: "81 Other Services (except Public Administration)", description: "Watch, Clock and Jewelry Repair", approvalNeeded: false },
  { code: "8114B", sector: "81 Other Services (except Public Administration)", description: "Furniture Reupholster, Repair, and Refinishing", approvalNeeded: false },
  { code: "8114C", sector: "81 Other Services (except Public Administration)", description: "Shoe Repair Shops, Shoeshine Parlors, and Hat Cleaning Shops", approvalNeeded: false },
  { code: "81211", sector: "81 Other Services (except Public Administration)", description: "Hair, Nail, and Skin Care Services", approvalNeeded: false },
  { code: "8121A", sector: "81 Other Services (except Public Administration)", description: "Massage Parlors", approvalNeeded: false },
  { code: "8121B", sector: "81 Other Services (except Public Administration)", description: "Health and Beauty Spas", approvalNeeded: false },
  { code: "8122", sector: "81 Other Services (except Public Administration)", description: "Death Care Services", approvalNeeded: false },
  { code: "8123", sector: "81 Other Services (except Public Administration)", description: "Drycleaning and Laundry Services", approvalNeeded: false },
  { code: "8123A", sector: "81 Other Services (except Public Administration)", description: "Laundromats", approvalNeeded: false },
  { code: "8123B", sector: "81 Other Services (except Public Administration)", description: "Dry Cleaners", approvalNeeded: false },
  { code: "81292", sector: "81 Other Services (except Public Administration)", description: "Photo Developing, Photofinishing Laboratories", approvalNeeded: false },
  { code: "8129E", sector: "81 Other Services (except Public Administration)", description: "Other Personal Services", approvalNeeded: false },
  { code: "8134", sector: "81 Other Services (except Public Administration)", description: "Civic and Social Organizations", approvalNeeded: false },
  { code: "8134A", sector: "81 Other Services (except Public Administration)", description: "Automobile Associations", approvalNeeded: false },
  { code: "81391", sector: "81 Other Services (except Public Administration)", description: "Business Associations", approvalNeeded: false },
  { code: "81392", sector: "81 Other Services (except Public Administration)", description: "Professional Organizations", approvalNeeded: false },
  { code: "81393", sector: "81 Other Services (except Public Administration)", description: "Labor Unions and Similar Labor Organizations", approvalNeeded: false },
  { code: "81399", sector: "81 Other Services (except Public Administration)", description: "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations)", approvalNeeded: false },
  { code: "921", sector: "92 Public Administration", description: "Executive, Legislative, and Other General Government Support", approvalNeeded: true },
  { code: "921A", sector: "92 Public Administration", description: "US Federal Government", approvalNeeded: true },
  { code: "921B", sector: "92 Public Administration", description: "Court Costs", approvalNeeded: true },
  { code: "921C", sector: "92 Public Administration", description: "Tax Payments", approvalNeeded: true },
  { code: "92219", sector: "92 Public Administration", description: "Other Justice, Public Order, and Safety Activities", approvalNeeded: true },
  { code: "922A", sector: "92 Public Administration", description: "Fines and Penalties of Any Kind", approvalNeeded: true },
  { code: "92B", sector: "92 Public Administration", description: "Other Public Administrations", approvalNeeded: true },
];

export const INDUSTRY_CODE_VALUES = INDUSTRY_CODES.map((i) => i.code) as [
  string,
  ...string[],
];

export function industryCodeLabel(code: string): string {
  const found = INDUSTRY_CODES.find((i) => i.code === code);
  return found ? `${found.code} — ${found.description}` : code;
}

// Grouped by sector, in the source table's order (sectors are already
// contiguous there) — feeds the business-activity select's <optgroup>s.
export const INDUSTRY_CODE_GROUPS: { sector: string; codes: IndustryCode[] }[] =
  INDUSTRY_CODES.reduce<{ sector: string; codes: IndustryCode[] }[]>((groups, entry) => {
    const last = groups[groups.length - 1];
    if (last && last.sector === entry.sector) {
      last.codes.push(entry);
    } else {
      groups.push({ sector: entry.sector, codes: [entry] });
    }
    return groups;
  }, []);
